name: parse_sdk_wrapper
version: 0.0.1-dev
description: Parse SDK for JavaScript wrapper for Dart
author: Cristian M Guerrero <guerrero.chavez.cristian@gmail.com>
homepage: https://github.com/google/chartjs.dart/
environment:
  sdk: '>=1.13.1 <3.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
